services:
  postgres-courier:
    image: postgres:16-alpine
    container_name: postgres-courier
    restart: unless-stopped
    environment:
      POSTGRES_DB: courier-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "@KeyDev"
    ports:
      - "5485:5432"
    volumes:
      - postgres_courier_data:/var/lib/postgresql/data
    networks:
      - delivery-network

  postgres-courier-test:
    image: postgres:16-alpine
    container_name: postgres-courier-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: courier-db-test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "@KeyDev"
    ports:
      - "5487:5432"
    volumes:
      - postgres_courier_data_test:/var/lib/postgresql/data
    networks:
      - delivery-network

  postgres-delivery-tracking:
    image: postgres:16-alpine
    container_name: postgres-delivery-tracking
    restart: unless-stopped
    environment:
      POSTGRES_DB: tracking-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "@KeyDev"
    ports:
      - "5486:5432"
    volumes:
      - postgres_delivery_tracking_data:/var/lib/postgresql/data
    networks:
      - delivery-network

  postgres-delivery-tracking-test:
    image: postgres:16-alpine
    container_name: postgres-delivery-tracking-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: tracking-test-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "@KeyDev"
    ports:
      - "5488:5432"
    volumes:
      - postgres_delivery_tracking_test_data:/var/lib/postgresql/data
    networks:
      - delivery-network
volumes:
  postgres_courier_data:
  postgres_delivery_tracking_data:
  postgres_courier_data_test:
  postgres_delivery_tracking_test_data:
networks:
  delivery-network:
    driver: bridge
