CREATE TABLE delivery
(
    id                       UUID NOT NULL PRIMARY KEY,
    courier_id               UUID,
    placed_at                TIMESTAMP WITH TIME ZONE,
    assigned_at              TIMESTAMP WITH TIME ZONE,
    expected_delivery_at     TIMESTAMP WITH TIME ZONE,
    fulfilled_at             TIMESTAMP WITH TIME ZONE,
    distance_fee             NUMERIC(19, 2),
    courier_payout           NUMERIC(19, 2),
    total_cost               NUMERIC(19, 2),
    total_items              INTEGER,
    status                   VARCHAR(50),
    sender_zip_code          VARCHAR(255),
    sender_street_address    VARCHAR(255),
    sender_street_number     VARCHAR(255),
    sender_city              VARCHAR(255),
    sender_state             VARCHAR(255),
    sender_country           VARCHAR(255),
    sender_complement        VARCHAR(255),
    sender_name              VARCHAR(255),
    sender_phone_number      VARCHAR(255),
    recipient_zip_code       VARCHAR(255),
    recipient_street_address VARCHAR(255),
    recipient_street_number  VARCHAR(255),
    recipient_city           VARCHAR(255),
    recipient_state          VARCHAR(255),
    recipient_country        VARCHAR(255),
    recipient_complement     VARCHAR(255),
    recipient_name           VARCHAR(255),
    recipient_phone_number   VARCHAR(255)
);